###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "name",
  "spicy": true,
  "amount": 12.0,
  "veggie": true
}

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "name2",
  "spicy": false,
  "amount": 12.0,
  "veggie": true
}

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "name3",
  "spicy": true,
  "amount": 12.0,
  "veggie": false
}

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "name4",
  "spicy": false,
  "amount": 12.0,
  "veggie": false
}

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "name5",
  "spicy": false,
  "amount": 12.0,
  "veggie": false
}

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "name6",
  "spicy": false,
  "amount": 12.0,
  "veggie": false
}

###

PATCH http://localhost:8080/api/ingredients/5
Content-Type: application/json

{
  "id": 5,
  "name": "new_name_patch",
  "spicy": true,
  "amount": 12.0,
  "veggie": true
}

###
GET http://localhost:8080/api/ingredients?page=0&size=5

###
GET http://localhost:8080/api/ingredients?page=1&size=5
###

DELETE http://localhost:8080/api/ingredients/5


###
POST http://localhost:8080/api/pizzas
Content-Type: application/json

{
  "name": "pizza1",
  "description": "desc1",
  "veggie": true,
  "ingredients": [
    {
      "id": 1,
      "name": "name",
      "spicy": true,
      "amount": 12.0,
      "veggie": true
    },
    {
      "id": 2,
      "name": "name2",
      "spicy": false,
      "amount": 12.0,
      "veggie": true
    }
  ]
}

###
PUT http://localhost:8080/api/pizzas/7
Content-Type: application/json

{
  "id": 7,
  "name": "pizza1_edited",
  "description": "desc1",
  "veggie": true,
  "ingredients": [
    {
      "id": 1,
      "name": "name",
      "spicy": true,
      "amount": 12.0,
      "veggie": true
    },
    {
      "id": 2,
      "name": "name2",
      "spicy": false,
      "amount": 12.0,
      "veggie": true
    },
    {
      "id": 3,
      "name": "name3",
      "spicy": true,
      "amount": 12.0,
      "veggie": false
    }
  ]
}

###


POST http://localhost:8080/api/pizzas
Content-Type: application/json

{
  "name": "pizza1",
  "description": "desc1",
  "veggie": true,
  "ingredients": [
    {
      "id": 1,
      "name": "name",
      "spicy": true,
      "amount": 12.0,
      "veggie": true
    },
    {
      "id": 3,
      "name": "name3",
      "spicy": true,
      "amount": 12.0,
      "veggie": false
    }
  ]
}

###
POST http://localhost:8080/api/pizzas
Content-Type: application/json

{
  "name": "pizza2",
  "description": "desc2",
  "veggie": false,
  "ingredients": [
    {
      "id": 1,
      "name": "name",
      "spicy": true,
      "amount": 12.0,
      "veggie": true
    },
    {
      "id": 2,
      "name": "name2",
      "spicy": false,
      "amount": 12.0,
      "veggie": true
    },
    {
      "id": 6,
      "name": "name6",
      "spicy": false,
      "amount": 12.0,
      "veggie": false
    }
  ]
}

###

GET http://localhost:8080/api/pizzas/

###

GET http://localhost:8080/api/pizzas/compare?pizza1=7&pizza2=8

###
DELETE http://localhost:8080/api/pizzas/8

###

GET http://localhost:8080/api/ingredients?page=0&size=5

###
